name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Start backend
        run: |
          pm2 delete backend || true
          pm2 start npm --name "backend" -- start