name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, backend]

    steps:
      - name: Clone or Update Backend
        run: |
          if [ ! -d "/home/shanmugavel/backend/.git" ]; then
            rm -rf /home/shanmugavel/backend
            git clone https://github.com/GWC-Data/nea_backend /home/shanmugavel/backend
          fi

          cd /home/shanmugavel/backend
          git fetch origin
          git reset --hard origin/main

      - name: Install Dependencies
        run: |
          cd /home/shanmugavel/backend
          npm install

      - name: Build Backend
        run: |
          cd /home/shanmugavel/backend
          npm run build

      - name: Restart Backend with PM2
        run: |
          cd /home/shanmugavel/backend

          pm2 describe backend > /dev/null 2>&1

          if [ $? -eq 0 ]; then
            pm2 restart backend
          else
            pm2 start ./dist/index.js \
              --name "backend" \
              --interpreter ./node_modules/.bin/nodemon \
              --node-args="-r @babel/register -r ./env/config.js" \
              --watch
          fi

          pm2 save