name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, backend]

    steps:
      - name: Clone or Update Backend
        run: |
          if [ ! -d "/home/shanmugavel/backend" ]; then
            git clone https://github.com/GWC-Data/nea_backend /home/shanmugavel/backend
          fi

          cd /home/shanmugavel/backend
          git pull origin main

      - name: Install & Start Backend
        run: |
          cd /home/shanmugavel/backend
          npm install
          pm2 restart backend || pm2 start npm --name "backend" -- start
          pm2 save